version: "3.8"

services:
  spotify-sync:
    image: undermix/spotify_sync:latest
    container_name: spotify-sync
    ports:
      - "8000:8000"
    volumes:
      - /path/to/data/music:/music
      - /path/to/data/playlists:/playlists
      - /path/to/data/db:/app/data
    environment:
      - TZ=Europe/Rome
      - SPM_SLSKD_URL=http://192.168.1.100:5030
      - SPM_SLSKD_API_KEY=
      - SPM_PROWLARR_URL=http://192.168.1.100:9696
      - SPM_PROWLARR_API_KEY=
      - SPM_QBITTORRENT_URL=http://192.168.1.100:8080
      - SPM_QBITTORRENT_USERNAME=admin
      - SPM_QBITTORRENT_PASSWORD=adminadmin
      - SPM_MUSIC_PATH=/music
      - SPM_PLAYLISTS_PATH=/playlists
      - SPM_DB_PATH=/app/data/spm.db
      - SPM_LOG_LEVEL=INFO
    restart: unless-stopped