services:
  spotify-sync:
    container_name: spotify-sync
    image: undermix/spotify_sync:latest
    restart: unless-stopped
    ports:
      - "8201:8000"
    volumes:
      - /mnt/wd-14tb/Spotify/music:/music
      - /mnt/wd-14tb/Spotify/playlist:/playlists
      - data:/app/data
    environment:
      - TZ=Europe/Rome
      - SPM_SLSKD_URL=http://192.168.1.110:5030
      - SPM_SLSKD_API_KEY=${SLSKD_API_KEY}
      - SPM_PROWLARR_URL=http://192.168.1.110:9696
      - SPM_PROWLARR_API_KEY=${PROWLARR_API_KEY}
      - SPM_QBITTORRENT_URL=http://192.168.1.110:30007
      - SPM_QBITTORRENT_USERNAME=${QBITTORRENT_USER}
      - SPM_QBITTORRENT_PASSWORD=${QBITTORRENT_PASSWORD}
      - SPM_MUSIC_PATH=/music
      - SPM_PLAYLISTS_PATH=/playlists
      - SPM_DB_PATH=/app/data/spm.db
      - SPM_LOG_LEVEL=DEBUG

volumes:
  data:
